# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

FROM jupyter/minimal-notebook

# Become root to do the apt-gets
USER root

RUN apt-get update && \
		apt-get install -y curl && \
		curl --silent --location https://deb.nodesource.com/setup_0.12 | sudo bash - && \
		apt-get install --yes nodejs && \
		npm install -g bower

# Do the pip installs as the unprivileged notebook user
USER jovyan

# Install a collection of nbextensions
#RUN pip install https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tarball/master && \
#    jupyter contrib nbextension install --user

#RUN pip install jupyter_nbextensions_configurator && \
#    jupyter nbextensions_configurator enable --user

ARG IPYWIDGETS_VER
RUN pip install "ipywidgets==$IPYWIDGETS_VER"

# Install RISE
RUN pip install RISE && \
    jupyter-nbextension install rise --py --sys-prefix && \
    jupyter-nbextension enable rise --py --sys-prefix

# Install dashboard layout and preview within Jupyter Notebook
ARG DASHBOARDS_VER
RUN pip install "jupyter_dashboards==$DASHBOARDS_VER" && \
	jupyter dashboards quick-setup --sys-prefix

RUN pip install "git+https://github.com/jupyter/kernel_gateway_demos.git#egg=nb2kg&subdirectory=nb2kg" && \
    jupyter serverextension enable --py nb2kg --sys-prefix

# Install content management to support dashboard bundler options
ARG CMS_VER
ARG BUNDLER_VER
RUN pip install "jupyter_cms==$CMS_VER" && \
	jupyter cms quick-setup --sys-prefix
RUN pip install "jupyter_dashboards_bundlers==$BUNDLER_VER" && \
	jupyter dashboards_bundlers quick-setup --sys-prefix
RUN jupyter nbextension enable --py --sys-prefix widgetsnbextension

ADD notebooks/ /home/jovyan/work
USER root
RUN chown -R jovyan /home/jovyan/work
USER jovyan

# Stay as jovyan in the newer docker stack images

CMD ["jupyter", "notebook", "--port=3010", "--ip=0.0.0.0", "--no-browser", "--notebook-dir=/home/jovyan/work", \
    	"--NotebookApp.password=''", \
    	"--NotebookApp.token=''", \
        "--NotebookApp.session_manager_class=nb2kg.managers.SessionManager", \
        "--NotebookApp.kernel_manager_class=nb2kg.managers.RemoteKernelManager", \
        "--NotebookApp.kernel_spec_manager_class=nb2kg.managers.RemoteKernelSpecManager"]
